name: Dump freeproxylists.net

# on:
#  schedule:
#    - cron:  '0 3 * * *'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install chromium
      run: sudo apt install chromium-browser

    - name: Dump webpage
      run: |
        sudo chmod -R 777 /run/user
        chromium --headless --disable-gpu-sandbox --lang=en --dump-dom "http://www.freeproxylists.net/?pr=HTTPS&s=u" > proxy_list.html