name: Dump freeproxylists.net

#on: [workflow_dispatch]
on:
  schedule:
    - cron:  '15 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install chromium
      run: sudo apt install chromium-browser

    - name: Dump webpage
      run: sudo chromium --headless --no-sandbox --lang=en --dump-dom "http://www.freeproxylists.net/?pr=HTTPS&s=u" > proxy-list.html

    - name: Publish proxy list
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add proxy-list.html
        git commit --allow-empty -m "CI: Proxy list"
        git push