name: Dump freeproxylists.net

# on:
#  schedule:
#    - cron:  '0 3 * * *'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install chromium
      run: sudo apt install chromium-browser

    - name: Dump webpage
      run: |
        chromium --headless --lang=en --dump-dom "http://www.freeproxylists.net/?pr=HTTPS&s=u" > proxy-list.html
        cat proxy-list.html

    - name: Publish proxy list
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add proxy-list.html
        git commit --allow-empty -m "CI: Proxy list"
        git push