name: Dump freeproxylists.net

# on:
#  schedule:
#    - cron:  '0 3 * * *'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Drivers
      run: sudo apt install mesa-va-drivers libva-drm2 libva-x11-2

    - name: Install chromium
      run: sudo apt install chromium-browser

    - name: Dump webpage
      run: chromium --headless --ignore-gpu-blacklist --ignore-gpu-blocklist --enable-accelerated-video-decode --use-gl=egl --lang=en --dump-dom "http://www.freeproxylists.net/?pr=HTTPS&s=u" > proxy_list.html