name: Dump freeproxylists.net

# on:
#  schedule:
#    - cron:  '0 3 * * *'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install chromium
      run: sudo apt install chromium-browser

    - name: Dump webpage
      run: chromium --headless --ignore-gpu-blocklist --use-gl=desktop --enable-accelerated-video-decode --enable-features=VaapiVideoDecoder --lang=en --dump-dom "http://www.freeproxylists.net/?pr=HTTPS&s=u" > proxy_list.html