name: Dump freeproxylists.net

# on:
#  schedule:
#    - cron:  '0 3 * * *'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install chromium
      run: sudo apt install chromium-browser